image: node:24

stages:
  - build
  - test

cache:
  key:
    files:
      - dotaHeroes/package-lock.json
  paths:
    - dotaHeroes/node_modules/

build_job:
  stage: build
  script:
    - cd dotaHeroes
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dotaHeroes/dist/

test_job:
  stage: test
  script:
    - cd dotaHeroes
    - npm ci
    - npm run test
