name: Node.js CI/CD to Fly.io

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dotaHeroes 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: ./dotaHeroes/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm run test
  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dotaHeroes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}